---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  triggers:
    - bindings:
        - name: github-binding
      template:
        name: template-cra
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gl-ci-listener
spec:
  triggers:
    - bindings:
        - name: gl-ci-binding
      template:
        name: template-cra
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gl-pr-listener
spec:
  triggers:
    - bindings:
        - name: gl-pr-binding
      template:
        name: template-cra
